receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource:
    attributes:
      - action: insert
        key: loki.format
        value: raw
      - action: insert
        key: loki.resource.labels
        value: service.name, app, runtime

  batch:
    timeout: 10s
    send_batch_size: 1024
    send_batch_max_size: 51200

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service:
  pipelines:      
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [logging, loki]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
      
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]    