server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: app-dev-logs
        __path__: "/var/log/MyAppLogs/*.log"
